### ISSUE TITLE
license info mismatch between `README.md` and `Cargo.toml`

### ISSUE THREAD

**Issue by fogti** [irrustible/futures-micro#5]
In `README.md`, it is stated that `futures-micro` is licensed under `MIT OR Apache-2.0`, but in `Cargo.toml`, license is set to `MPL-2.0`. This should be fixed.

**Comment by jjl** [comment]
Ugh.

Do we still have any actual code from futures{,-lite} remaining?

**Comment by fogti** [comment]
I think `pending` & `ready` are remaining...

**Comment by jjl** [comment]
iirc, they remain as deprecated functions, which you're suggesting taking out in the other thread. it would seem to solve two problems at once :)

**Comment by fogti** [comment]
btw. I'm unsure if releasing `futures-micro` solely under `MPL-2.0` is really a good idea. I'm unsure about compatibility with `Apache-2.0` licensed- and `LGPLv3` licensed-projects. Additionally, it would mean that replacing `futures-lite` with `futures-micro` usage is not always possible because of license issues (as the `MPL-2.0` seems to be more restrictive than the `MIT OR Apache-2.0` combo), I suppose.

**Comment by jjl** [comment]
indeed, the mpl is basically a copyleft license. what it does differently than lgpl is draws a boundary at the file as to what counts as including the code.

The MIT license doesn't have the protection against software patents that the others have. I'd be open to relicensing under apache2, but i'd be against using MIT.

i'm also considering going completely the other way on some of my projects, using source visible (but not open source) arrangements or such. but this is a bit of a foundational library, so i'm disinclined to go that way here.

**Comment by fogti** [comment]
I would recommend releasing it under `Apache-2.0` (this also means that I accept a relicense of all patches and work I contributed to this project to be relicensed under `Apache-2.0`).

**Comment by jjl** [comment]
Okay, well I consent as above.

There are two other contributors to this repository, of them:
* stjepang's patch was trivial, not that i think he'd object anyway
* i can't see @r3v2d0g having a problem, but please tell us so anyway, matthieu.

**Comment by fogti** [comment]
It may be desirable to license this not under simply `Apache-2.0` but under `Apache-2.0 WITH LLVM-Exception` (https://spdx.org/licenses/LLVM-exception.html), as this allows GPLv2 compatibility, but I'm not sure if you would be ok with this, as I'm unsure how it would affect the anti software patent stuff.

**Comment by jjl** [comment]
who could pass up an opportunity to be depended upon by code in the linux kernel source tree?
