### ISSUE TITLE
[planning] Remove deprecated functions

### ISSUE THREAD

**Issue by fogti** [irrustible/futures-micro#6]
Currently, the futures-micro:main branch is in a somewhat undesired state. The code declares some functions as deprecated, but the code itself is also somewhat incompatible to `v0.3.*`, which means it would need 2 minor version bumps (1 to declare the functions as deprecated, 1 to finally remove them).
I'm unsure if it would be possible to speed this up. I would like these superfluous functions to be removed basically "right now", so that we can release an `v0.4.0` without them. But to guarantee that this goes smoothly, we would basically need to patch all dependent crates which use these functions and remove those usages before releasing the `v0.4` version. The migration recommendations in `README.md` should be left there until version `0.5`.

Dependent crates (search queries: [github.com](https://github.com/search?p=3&q=futures-micro&type=Code), [crates.io](https://crates.io/crates/futures-micro/reverse_dependencies)):
* [X] [`async-oneshot`](https://github.com/irrustible/async-oneshot), patched in [#12](https://github.com/irrustible/async-oneshot/pull/12)
* [ ] [`async-oneshot-local`](https://github.com/irrustible/async-oneshot-local), "but" currently broken regardless of that.
* [X] https://github.com/r3v2d0g/ufut, nothing to patch (just reexports anything via wildcard)
* [ ] [`async-spsc`](https://github.com/irrustible/async-spsc), needs to be patched, [#1](https://github.com/irrustible/async-spsc/pull/1)
* [X] https://github.com/jacobrosenthal/sophon_tweets, nothing to patch (only uses `or!`)
* [X] https://github.com/YZITE/encsess2, nothing to patch (only uses `poll_fn`)
* [X] https://github.com/YZITE/yxd-auth, nothing to patch (only uses `poll_fn`)

**Comment by jjl** [comment]
i don't think i've released either of the two outstanding versions to crates yet, and as you note, i haven't even made one of them work yet, so don't worry about those.

we're still pre-1.0, so we *could* just remove them. most of the downloads are i suspect related to async-oneshot, in any case.

i'll leave it to you to decide what to do, since you've been more of a maintainer of this lib recently than i have.
